"""Lifecycle helpers for lean, isolated multi-agent Pulp environments."""

import os
import re
import shutil
import socket
import subprocess

from oci_env.logger import logger
from oci_env.utils import (
    Compose,
    exit_with_error,
    get_config,
    get_oci_env_path,
    read_env_file,
)


AGENT_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")
DEFAULT_PORT_START = 5100
DEFAULT_PORT_END = 5199
AGENT_ENV_FILENAME = "compose.env"
AGENT_OVERLAY_FILENAME = "plugin_volumes_compose.yaml"
GENERATOR_REPO = "pulp-openapi-generator"

# Agent environments always use podman (rootless-friendly for parallel stacks).
AGENT_COMPOSE_BINARY = "podman"

# Keys owned by agent create; --env cannot override these.
_AGENT_LOCKED_KEYS = {
    "OCI_AGENT_ID",
    "OCI_AGENT_HOST_SRC_DIR",
    "OCI_AGENT_PLUGIN_PATHS",
    "OCI_AGENT_VOLUME_OVERLAY",
    "COMPOSE_BINARY",
    "COMPOSE_PROJECT_NAME",
    "DEV_SOURCE_PATH",
    "SRC_DIR",
    "OCI_ENV_DIR",
    "OCI_ENV_CONFIG_FILE",
}


def agent_project_name(agent_id):
    return f"agent_{agent_id}"


def agent_compiled_dir(oci_env_path, agent_id):
    """Per-agent directory under .compiled/ (also used as SRC_DIR and compose project)."""
    return os.path.join(oci_env_path, ".compiled", agent_project_name(agent_id))


def agent_env_path(oci_env_path, agent_id):
    return os.path.join(agent_compiled_dir(oci_env_path, agent_id), AGENT_ENV_FILENAME)


def agent_volume_overlay_path(oci_env_path, agent_id):
    return os.path.join(agent_compiled_dir(oci_env_path, agent_id), AGENT_OVERLAY_FILENAME)


def validate_agent_id(agent_id):
    if not AGENT_ID_RE.match(agent_id):
        exit_with_error(
            f"Invalid agent id {agent_id!r}. Use letters, numbers, '_', '-', or '.' "
            "(must start with alphanumeric)."
        )


def list_agent_ids(oci_env_path):
    compiled = os.path.join(oci_env_path, ".compiled")
    if not os.path.isdir(compiled):
        return []
    ids = []
    for name in sorted(os.listdir(compiled)):
        env_path = os.path.join(compiled, name, AGENT_ENV_FILENAME)
        if not os.path.isfile(env_path):
            continue
        data = read_env_file(env_path)
        agent_id = data.get("OCI_AGENT_ID")
        if agent_id:
            ids.append(agent_id)
    return ids


def load_agent_env(oci_env_path, agent_id):
    path = agent_env_path(oci_env_path, agent_id)
    if not os.path.isfile(path):
        exit_with_error(f"Agent {agent_id!r} does not exist (missing {path})")
    return path, read_env_file(path)


def write_env_file(path, values):
    lines = [
        "# AUTOGENERATED by oci-env agent",
        f"# Agent id: {values.get('OCI_AGENT_ID', '')}",
        "",
    ]
    # Stable order for core keys, then any extras (e.g. from --env).
    preferred = (
        "OCI_AGENT_ID",
        "COMPOSE_PROFILE",
        "DEV_SOURCE_PATH",
        "COMPOSE_PROJECT_NAME",
        "API_PORT",
        "SRC_DIR",
        "COMPOSE_BINARY",
        "API_HOST",
        "API_PROTOCOL",
        "OCI_AGENT_VOLUME_OVERLAY",
        "OCI_AGENT_PLUGIN_PATHS",
        "OCI_AGENT_HOST_SRC_DIR",
    )
    written = set()
    for key in preferred:
        if key in values and values[key] not in (None, ""):
            lines.append(f"{key}={values[key]}")
            written.add(key)
    for key in sorted(values.keys()):
        if key in written or values[key] in (None, ""):
            continue
        lines.append(f"{key}={values[key]}")

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def _port_in_use(port, host="127.0.0.1"):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind((host, port))
        except OSError:
            return True
    return False


def allocated_ports(oci_env_path):
    ports = set()
    for agent_id in list_agent_ids(oci_env_path):
        _, data = load_agent_env(oci_env_path, agent_id)
        port = data.get("API_PORT")
        if port and str(port).isdigit():
            ports.add(int(port))
    return ports


def allocate_port(oci_env_path, preferred=None, start=DEFAULT_PORT_START, end=DEFAULT_PORT_END):
    used = allocated_ports(oci_env_path)
    if preferred is not None:
        preferred = int(preferred)
        if preferred in used:
            exit_with_error(f"Port {preferred} is already allocated to another agent")
        if _port_in_use(preferred):
            exit_with_error(f"Port {preferred} is already in use on the host")
        return preferred

    for port in range(start, end + 1):
        if port in used:
            continue
        if not _port_in_use(port):
            return port
    exit_with_error(f"No free agent API ports left in range {start}-{end}")


def host_compose_config(oci_env_path):
    """
    Load the user's normal compose.env/.compose.env if present.

    Falls back to empty dict when no host env file exists (agent create must
    still work without one). Environment variable overrides are applied the
    same way as get_config() when a file is found.
    """
    for name in ("compose.env", ".compose.env"):
        path = os.path.join(oci_env_path, name)
        if os.path.isfile(path):
            return get_config(path)
    return {}


def default_host_src_dir(oci_env_path):
    """Best-effort SRC_DIR from an existing compose.env, else parent of oci_env."""
    fallback = os.path.abspath(os.path.join(oci_env_path, ".."))
    cfg = host_compose_config(oci_env_path)
    return cfg.get("SRC_DIR") or fallback


def parse_env_arg(value):
    """Parse KEY=VALUE from --env."""
    if "=" not in value:
        exit_with_error(f"Invalid --env {value!r}. Expected KEY=VALUE.")
    key, val = value.split("=", 1)
    key = key.strip()
    if not key:
        exit_with_error(f"Invalid --env {value!r}: key is empty")
    if key in _AGENT_LOCKED_KEYS:
        exit_with_error(
            f"--env cannot set {key}; it is managed by oci-env agent create"
        )
    return key, val


def collect_env_overrides(args):
    overrides = {}
    for value in getattr(args, "env_vars", None) or []:
        key, val = parse_env_arg(value)
        overrides[key] = val
    return overrides


def resolve_repo_path(host_src_dir, repo):
    path = os.path.join(host_src_dir, repo)
    if not os.path.isdir(path):
        exit_with_error(f"Repository checkout not found at {path}")
    if not os.path.isdir(os.path.join(path, ".git")) and not os.path.isfile(
        os.path.join(path, ".git")
    ):
        # worktree checkouts have a .git file; plain dirs without git are invalid
        exit_with_error(f"{path} is not a git repository")
    return path


def parse_plugins_arg(spec, host_src_dir):
    """
    Parse --plugins as colon-separated PLUGIN[=PATH] entries.

    Examples:
      pulpcore
      pulpcore:pulp_rpm
      pulpcore=~/.cursor/worktrees/pulpcore/my-wt
      pulpcore=/path/to/wt:pulp_rpm
    """
    if not spec or not spec.strip():
        exit_with_error("At least one plugin is required via --plugins")

    plugins = []
    plugin_paths = {}
    for part in spec.split(":"):
        part = part.strip()
        if not part:
            continue
        if "=" in part:
            plugin, path = part.split("=", 1)
            plugin = plugin.strip()
            path = os.path.abspath(os.path.expanduser(path.strip()))
            if not plugin:
                exit_with_error(f"Invalid --plugins entry {part!r}: plugin name is empty")
            if not os.path.isdir(path):
                exit_with_error(f"Plugin path for {plugin!r} is not a directory: {path}")
        else:
            plugin = part
            path = resolve_repo_path(host_src_dir, plugin)
        if plugin in plugin_paths:
            exit_with_error(f"Plugin {plugin!r} listed more than once in --plugins")
        plugins.append(plugin)
        plugin_paths[plugin] = path

    if not plugins:
        exit_with_error("At least one plugin is required via --plugins")
    return plugins, plugin_paths


def encode_plugin_paths(plugin_paths):
    """Serialize plugin->path mapping for the agent env file."""
    return ",".join(f"{plugin}={path}" for plugin, path in sorted(plugin_paths.items()))


def generator_checkout_path(host_src_dir):
    """Return the real path to pulp-openapi-generator under host_src_dir, or None."""
    if not host_src_dir:
        return None
    path = os.path.join(host_src_dir, GENERATOR_REPO)
    if os.path.isdir(path):
        return os.path.realpath(path)
    return None


def agent_generator_dir(src_dir):
    return os.path.join(src_dir, GENERATOR_REPO)


def agent_has_generator_copy(src_dir):
    """True if create copied pulp-openapi-generator into the agent SRC_DIR."""
    return os.path.isfile(os.path.join(agent_generator_dir(src_dir), "generate.sh"))


def copy_generator_checkout(host_src_dir, compiled_dir):
    """
    Copy pulp-openapi-generator into the agent compiled dir.

    Skips .git and previously generated *-client trees so each agent gets an
    isolated working copy without sharing host generator state.
    """
    src = generator_checkout_path(host_src_dir)
    if not src:
        return None
    dest = agent_generator_dir(compiled_dir)
    ignore = shutil.ignore_patterns(
        ".git",
        ".github",
        "*-client",
        "__pycache__",
        ".pytest_cache",
        "api.json",
        "patched-api.json",
    )
    try:
        shutil.copytree(src, dest, ignore=ignore)
    except OSError as exc:
        exit_with_error(f"Failed to copy {GENERATOR_REPO} from {src} to {dest}: {exc}")
    logger.info(f"Copied {GENERATOR_REPO} to {dest}")
    return dest


def write_plugin_volume_overlay(overlay_path, plugin_paths):
    """
    Write a compose overlay that bind-mounts plugin checkouts into /src/<plugin>.

    Nested under the base `{SRC_DIR}:/src` mount; podman creates the destination
    path when missing, so no host-side mount-point directories are required.
    """
    lines = [
        "# AUTOGENERATED by oci-env agent — bind mounts for plugin checkouts",
        "services:",
        "  pulp:",
        "    volumes:",
    ]
    for plugin, path in sorted(plugin_paths.items()):
        real = os.path.realpath(path)
        lines.append(f'      - "{real}:/src/{plugin}:z"')

    os.makedirs(os.path.dirname(overlay_path), exist_ok=True)
    with open(overlay_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    logger.info(f"Wrote plugin volume overlay: {overlay_path}")
    return overlay_path


def compose_for_agent(is_verbose, env_file):
    client = Compose(is_verbose, env_file)
    overlay = client.config.get("OCI_AGENT_VOLUME_OVERLAY")
    if overlay and os.path.isfile(overlay):
        client.compose_files.append(overlay)
        if is_verbose:
            logger.info(f"Including agent volume overlay: {overlay}")
    return client


def agent_status(oci_env_path, agent_id, env_data, is_verbose=False):
    """Return a short status string for an agent environment."""
    project = env_data.get("COMPOSE_PROJECT_NAME", agent_project_name(agent_id))
    cmd = [AGENT_COMPOSE_BINARY, "ps", "--filter", f"name={project}", "--format", "{{.Names}}"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError:
        return "unknown"

    names = [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    if not names:
        return "down"
    return "up"


def agent_create(args):
    oci_env_path = get_oci_env_path(args.is_verbose)
    validate_agent_id(args.agent_id)

    compiled_dir = agent_compiled_dir(oci_env_path, args.agent_id)
    env_path = agent_env_path(oci_env_path, args.agent_id)
    if os.path.exists(env_path) or (
        os.path.isdir(compiled_dir) and os.listdir(compiled_dir)
    ):
        exit_with_error(
            f"Agent {args.agent_id!r} already exists at {compiled_dir}"
        )

    host_src_dir = os.path.abspath(args.host_src_dir or default_host_src_dir(oci_env_path))
    plugins, plugin_paths = parse_plugins_arg(args.plugins, host_src_dir)
    env_overrides = collect_env_overrides(args)

    if "API_PORT" in env_overrides and args.port is not None:
        exit_with_error("Specify API port with either --port or --env API_PORT, not both")
    api_port = allocate_port(oci_env_path, preferred=env_overrides.get("API_PORT", args.port))

    project_name = agent_project_name(args.agent_id)
    compose_profile = env_overrides.get("COMPOSE_PROFILE") or "lean"

    os.makedirs(compiled_dir, exist_ok=True)
    overlay = write_plugin_volume_overlay(
        agent_volume_overlay_path(oci_env_path, args.agent_id),
        plugin_paths,
    )
    generator = copy_generator_checkout(host_src_dir, compiled_dir)
    if not generator:
        logger.warning(
            f"No {GENERATOR_REPO} checkout at "
            f"{os.path.join(host_src_dir, GENERATOR_REPO)}. "
            "oci-env agent generate-client will fail until you clone it and "
            "destroy/recreate this agent."
        )

    values = {
        "OCI_AGENT_ID": args.agent_id,
        "COMPOSE_PROFILE": compose_profile,
        "DEV_SOURCE_PATH": ":".join(plugins),
        "COMPOSE_PROJECT_NAME": project_name,
        "API_PORT": str(api_port),
        "SRC_DIR": compiled_dir,
        "COMPOSE_BINARY": AGENT_COMPOSE_BINARY,
        "API_HOST": "localhost",
        "API_PROTOCOL": "http",
        # Pulp refuses to start without this; --env can override.
        "PULP_SECRET_KEY": "dummy",
        "OCI_AGENT_HOST_SRC_DIR": host_src_dir,
        "OCI_AGENT_PLUGIN_PATHS": encode_plugin_paths(plugin_paths),
        "OCI_AGENT_VOLUME_OVERLAY": overlay,
    }

    # Apply user --env overrides (locked keys already rejected).
    values.update(env_overrides)

    write_env_file(env_path, values)
    print(f"Created agent {args.agent_id}")
    print(f"  env:     {env_path}")
    print(f"  project: {project_name}")
    print(f"  port:    {values['API_PORT']}")
    print(f"  src:     {compiled_dir}")
    print(f"  profile: {values['COMPOSE_PROFILE']}")
    print(f"  compose: {AGENT_COMPOSE_BINARY}")
    print(f"  plugins: {':'.join(plugins)}")
    for plugin in plugins:
        print(f"  {plugin}: {plugin_paths[plugin]}")
    if generator:
        print(f"  {GENERATOR_REPO}: {generator}")
    for key in sorted(env_overrides.keys()):
        print(f"  {key}={env_overrides[key]}")
    print(f"Start with: oci-env agent up {args.agent_id}")


def agent_up(args):
    oci_env_path = get_oci_env_path(args.is_verbose)
    env_path, _ = load_agent_env(oci_env_path, args.agent_id)
    client = compose_for_agent(args.is_verbose, env_path)

    up_cmd = ["up", "-d"]
    if args.build:
        up_cmd.append("--build")
    rc = client.compose_command(up_cmd, interactive=True)
    if rc != 0:
        exit(rc)

    client.poll(args.attempts, args.wait)
    api = "{}://{}:{}/".format(
        client.config["API_PROTOCOL"],
        client.config["API_HOST"],
        client.config["API_PORT"],
    )
    print(f"Agent {args.agent_id} is up at {api}")


def agent_down(args):
    oci_env_path = get_oci_env_path(args.is_verbose)
    env_path, _ = load_agent_env(oci_env_path, args.agent_id)
    try:
        client = compose_for_agent(args.is_verbose, env_path)
        rc = client.compose_command(["down"], interactive=True)
    except FileNotFoundError as exc:
        exit_with_error(f"compose binary unavailable: {exc}")
    exit(rc)


def agent_destroy(args):
    oci_env_path = get_oci_env_path(args.is_verbose)
    env_path, env_data = load_agent_env(oci_env_path, args.agent_id)
    compiled_dir = agent_compiled_dir(oci_env_path, args.agent_id)

    try:
        client = compose_for_agent(args.is_verbose, env_path)
        rc = client.compose_command(["down", "--volumes"], interactive=True)
        if rc != 0:
            logger.warning(
                f"compose down --volumes returned {rc}; continuing with agent cleanup"
            )
    except FileNotFoundError as exc:
        logger.warning(f"compose binary unavailable ({exc}); continuing with agent cleanup")
    except SystemExit:
        logger.warning("compose client setup failed; continuing with agent cleanup")

    # Remove the entire agent compiled directory (env, overlay, generator copy,
    # and any files written by parse_profiles). Never deletes bind-mount targets.
    if os.path.isdir(compiled_dir):
        shutil.rmtree(compiled_dir)
        logger.info(f"Removed agent compiled directory {compiled_dir}")
    elif os.path.isfile(env_path):
        os.remove(env_path)

    print(f"Destroyed agent {args.agent_id}")


def agent_ls(args):
    oci_env_path = get_oci_env_path(args.is_verbose)
    ids = list_agent_ids(oci_env_path)
    if not ids:
        print("No agent environments found.")
        return

    print(f"{'ID':<20} {'PORT':<8} {'STATUS':<8} {'PROJECT':<24} SRC_DIR")
    for agent_id in ids:
        _, data = load_agent_env(oci_env_path, agent_id)
        status = agent_status(oci_env_path, agent_id, data, args.is_verbose)
        print(
            f"{agent_id:<20} {data.get('API_PORT', '-'):<8} {status:<8} "
            f"{data.get('COMPOSE_PROJECT_NAME', '-'):<24} {data.get('SRC_DIR', '-')}"
        )


def agent_test(args):
    """
    Run tests against an agent environment.

    Functional tests execute inside the agent container, so they use that
    environment's live API (API_PORT/ creds from the agent env file).
    """
    oci_env_path = get_oci_env_path(args.is_verbose)
    env_path, env_data = load_agent_env(oci_env_path, args.agent_id)
    client = compose_for_agent(args.is_verbose, env_path)

    # Expose connection hints for tooling that reads the process environment.
    os.environ.setdefault("OCI_AGENT_ID", args.agent_id)
    os.environ.setdefault("PULP_API_HOST", env_data.get("API_HOST", "localhost"))
    os.environ.setdefault("PULP_API_PORT", str(env_data.get("API_PORT", "")))
    os.environ.setdefault(
        "PULP_API_ROOT",
        os.environ.get("PULP_API_ROOT", "/pulp/"),
    )
    os.environ.setdefault(
        "DJANGO_SUPERUSER_USERNAME",
        env_data.get("DJANGO_SUPERUSER_USERNAME", "admin"),
    )
    os.environ.setdefault(
        "DJANGO_SUPERUSER_PASSWORD",
        env_data.get("DJANGO_SUPERUSER_PASSWORD", "password"),
    )

    from oci_env.commands import test as run_test

    # Build a namespace compatible with commands.test
    class _TestArgs:
        pass

    test_args = _TestArgs()
    test_args.install_deps = args.install_deps
    test_args.test = args.test
    test_args.plugin = args.plugin
    # Drop a leading "--" separator commonly used before pytest paths.
    pytest_args = list(args.args or [])
    if pytest_args and pytest_args[0] == "--":
        pytest_args = pytest_args[1:]
    test_args.args = pytest_args
    test_args.privileged = args.privileged
    test_args.is_verbose = args.is_verbose

    if not test_args.plugin:
        # Default to the first DEV_SOURCE_PATH plugin for agent workflows.
        plugins = [p for p in env_data.get("DEV_SOURCE_PATH", "").split(":") if p]
        if len(plugins) == 1:
            test_args.plugin = plugins[0]
        else:
            exit_with_error(
                "Specify -p PLUGIN for agent test when DEV_SOURCE_PATH has multiple plugins"
            )

    print(
        f"Running {test_args.test} tests for {test_args.plugin} on agent {args.agent_id} "
        f"(API {env_data.get('API_PROTOCOL', 'http')}://{env_data.get('API_HOST', 'localhost')}:"
        f"{env_data.get('API_PORT')})"
    )
    run_test(test_args, client)


def agent_generate_client(args):
    oci_env_path = get_oci_env_path(args.is_verbose)
    env_path, env_data = load_agent_env(oci_env_path, args.agent_id)
    src_dir = env_data.get("SRC_DIR") or agent_compiled_dir(oci_env_path, args.agent_id)
    if not agent_has_generator_copy(src_dir):
        exit_with_error(
            f"{GENERATOR_REPO} was not copied when agent {args.agent_id} was created. "
            "Clone github.com/pulp/pulp-openapi-generator into the host source directory, "
            "then destroy and recreate the agent."
        )

    client = compose_for_agent(args.is_verbose, env_path)

    from oci_env.commands import generate_client

    class _Args:
        pass

    gargs = _Args()
    gargs.plugin = args.plugin
    gargs.language = args.language
    gargs.install_client = args.install_client
    gargs.is_verbose = args.is_verbose
    gargs.api_version = getattr(args, "api_version", "v3")
    generate_client(gargs, client)


def agent_dispatch(args):
    actions = {
        "create": agent_create,
        "up": agent_up,
        "down": agent_down,
        "destroy": agent_destroy,
        "ls": agent_ls,
        "test": agent_test,
        "generate-client": agent_generate_client,
    }
    action = getattr(args, "agent_action", None)
    if action not in actions:
        exit_with_error(f"Unknown agent action: {action}")
    actions[action](args)
