#!/bin/bash

set -e

NEWV=$1
CURV=$(python3 --version)
if [[ "${CURV//Python /}" == *"$NEWV"* ]]; then
    echo "using default python $CURV"
    exit 0
fi

echo "switching python to $NEWV"

rm -f /usr/local/bin/pip3
dnf install -y python${NEWV} python${NEWV}-pip python${NEWV}-devel
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${NEWV} 1
update-alternatives --set python3 /usr/bin/python${NEWV}
update-alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip-${NEWV} 1
update-alternatives --set pip3 /usr/bin/pip-${NEWV}
